# Generated by Django 4.2.6 on 2023-10-24 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last_name')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='age')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relations.teacher')),
            ],
        ),
    ]
