# Generated by Django 4.2.6 on 2023-10-31 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_study',
            field=models.BooleanField(default=True, verbose_name='is_study'),
        ),
    ]