# Generated by Django 4.2.6 on 2023-10-31 18:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0004_student_is_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='about_me',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]