version: '3.7'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis
#      - memcached
    networks:
      - main

  db:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
      - main

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/code
    ports:
      - '80:80'
    depends_on:
      - web
    networks:
      - main

#  memcached:
#    image: memcached
#    ports:
#      - '11211:11211'
#    networks:
#      - main

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
    networks:
      - main

  celery:
    build:
      context: .
    command: celery -A blog worker -l info
    depends_on:
      - redis
    volumes:
      - .:/code
    env_file:
      - .env
    networks:
      - main

  celery-beat:
    build:
      context: .
    command: ['./entrypoint_celery_beat.sh']
    depends_on:
      - web
    env_file:
      - .env
    networks:
      - main

networks:
  main:

volumes:
  db:
  nginx:
  celery: